logging:
  receivers:
    myapplogs:
      type: files
      include_paths:
        - /opt/your-app/app.log

  processors:
    parse_message:
      type: parse_json
      field: message
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
    reformat_timestamp:
      type: parse_timestamp
      field: jsonPayload.timestamp
      time_format: '%Y-%m-%dT%H:%M:%S.%fZ'
      timezone: UTC
      output_format: '%Y-%m-%dT%H:%M:%S.%LZ'
  service:
    pipelines:
      default_log_pipeline:
        receivers: [ myapplogs ]
        processors: [ parse_message, move_severity, reformat_timestamp ]

