name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: INTEGRATION TEST
    runs-on: ubuntu-latest
    

    steps:
      - name: Install MariaDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-server

      - name: Start MariaDB Service
        run: sudo service mariadb start

      - name: Set up MySQL Root Password
        run: |
          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'saikumar123';"

      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Integration Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/CSYE6225?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: saikumar123
        run: mvn -B verify

      - name: Run Packer init
        run: packer init packer/

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'

      - name: Build Packer Image
        run: |
          packer build -var 'source_file=/target/webapp-0.0.1-SNAPSHOT.jar' -var 'tmp_service_file=packer/your-app.service' packer/image.pkr.hcl
      
