name: MySQL Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  name: MySQL Integration Tests
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install MariaDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-server
          sudo mysql_secure_installation
          

      - name: Start MariaDB Service
        run: sudo systemctl start mariadb
          sudo mysql -u root -e "alter user 'root'@'localhost' identified by 'saikumar123' ;"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run Integration Tests
        run: mvn -B verify

      # Additional steps for deploying or other actions
