name: Packer Status Check

# Trigger: Run the workflow whenever a pull request is opened or modified
on:
  pull_request:
    branch: main

jobs:
  packer-checks:
    runs-on: ubuntu-latest  # OS environment to run on
    steps:
      - uses: actions/checkout@v3  # Checkout the repository
      - uses: hashicorp/setup-packer@v1  # Setup Packer
        with:
          version: latest  # Or a specific version

      # Step 1: Format Check
      - name: Run packer fmt
        run: packer fmt -check packer/ # -check flag makes it fail if changes are needed
        if: failure()            # Only run validate if fmt succeeded

      # Step 2: Validation Check
      - name: Run packer validate
        run: packer validate packer/  # Assuming your template is in the root
