name: Packer Status Check

# Trigger: Run the workflow whenever a pull request is opened or modified
on:
  pull_request:
    branch: main

jobs:
  packer-checks-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Step 1: Install Missing Plugins
      - name: Run packer init
        run: packer init packer/

      # Step 2: Format Check
      - name: Run packer fmt
        run: packer fmt -check packer/

      # Step 3: Validation Check
      - name: Run packer validate
        run: packer validate packer/
